"""empty message

Revision ID: 040ba8185928
Revises: 636e065cd1f8
Create Date: 2022-01-27 21:48:30.932998

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '040ba8185928'
down_revision = '636e065cd1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('statuss', sa.Boolean(), nullable=False))
    op.drop_column('language', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('language', 'statuss')
    # ### end Alembic commands ###
