"""empty message

Revision ID: 041651b617fc
Revises: d9e7b9767fa0
Create Date: 2022-04-05 20:13:27.110681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041651b617fc'
down_revision = 'd9e7b9767fa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_key')
    op.drop_column('item_subtype', 'image_key')
    op.drop_column('item_type', 'image_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type', sa.Column('image_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('item_subtype', sa.Column('image_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('item', sa.Column('image_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
