"""empty message

Revision ID: 05cc1a8cc229
Revises: 97be1251f26d
Create Date: 2022-01-19 20:35:40.559631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05cc1a8cc229'
down_revision = '97be1251f26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('statuss', sa.Boolean(), nullable=False))
    op.drop_column('payment_method', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payment_method', 'statuss')
    # ### end Alembic commands ###
