"""status_fixture_booking_status

Revision ID: 05d8a64b8cc7
Revises: bc33b3809d3f
Create Date: 2022-03-22 19:15:44.970392

"""
from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision = '05d8a64b8cc7'
down_revision = 'bc33b3809d3f'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("booking_status",))

    item_status = Table("booking_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Active",
                "color": "green",
            },
            {
                "name": "Closed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            }

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
