"""constraints updated for cascade

Revision ID: 06b7c1f08416
Revises: 1717694c77e3
Create Date: 2022-03-22 22:48:31.269744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b7c1f08416'
down_revision = '1717694c77e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_booking_status_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'booking_status', ['booking_status_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('item_item_status_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'item_status', ['item_status_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('order_order_status_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'order_status', ['order_status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_order_status_id_fkey', 'order', 'order_status', ['order_status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_item_status_id_fkey', 'item', 'item_status', ['item_status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_booking_status_id_fkey', 'booking', 'booking_status', ['booking_status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
