"""empty message

Revision ID: 0d3496a83f7f
Revises: e71e6a8e966a
Create Date: 2022-06-20 14:28:40.072244

"""
from alembic import op

from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision = '0d3496a83f7f'
down_revision = 'e71e6a8e966a'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("booking_status",))

    item_status = Table("booking_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Payment Pending",
                "color": "yellow",
            }
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
