"""default_payment

Revision ID: 1717694c77e3
Revises: 05d8a64b8cc7
Create Date: 2022-03-22 19:18:28.368421

"""
from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision = '1717694c77e3'
down_revision = '05d8a64b8cc7'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("payment_method",))

    item_status = Table("payment_method", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Stripe",
                "status": True,
            }
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
