"""empty message

Revision ID: 1bbad1f20e12
Revises: 1bf2ae40d10a
Create Date: 2021-11-25 00:47:10.774887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbad1f20e12'
down_revision = '1bf2ae40d10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('image'),
    sa.UniqueConstraint('price')
    )
    op.create_index(op.f('ix_item_updated_at'), 'item', ['updated_at'], unique=False)
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('subscription', sa.String(), nullable=False))
    op.add_column('user', sa.Column('status', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['subscription'])
    op.create_unique_constraint(None, 'user', ['status'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'status')
    op.drop_column('user', 'subscription')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.drop_index(op.f('ix_item_updated_at'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
