"""empty message

Revision ID: 1bf2ae40d10a
Revises: f1f1c8914e5f
Create Date: 2021-11-24 00:49:01.870305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf2ae40d10a'
down_revision = 'f1f1c8914e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email2_key', 'user', type_='unique')
    op.drop_column('user', 'email2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_email2_key', 'user', ['email2'])
    # ### end Alembic commands ###
