"""prices added

Revision ID: 1c4f75fa1d71
Revises: 5ba14c74688e
Create Date: 2022-03-27 16:27:11.334891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c4f75fa1d71'
down_revision = '5ba14c74688e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('effected_total_cost', sa.Float(), nullable=False))
    op.drop_column('order', 'actual_total_cost_after_tax')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('actual_total_cost_after_tax', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('order', 'effected_total_cost')
    # ### end Alembic commands ###
