"""prices added

Revision ID: 1cdd17e7b671
Revises: 1c4f75fa1d71
Create Date: 2022-03-27 16:40:38.594346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdd17e7b671'
down_revision = '1c4f75fa1d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('tax_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tax_amount')
    # ### end Alembic commands ###
