"""empty message

Revision ID: 1d10b735d95f
Revises: 648c25c348ca
Create Date: 2022-06-10 16:33:34.270888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d10b735d95f'
down_revision = '648c25c348ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_type_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_type_text_item_type_id'), 'item_type_text', ['item_type_id'], unique=True)
    op.create_index(op.f('ix_item_type_text_updated_at'), 'item_type_text', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_type_text_updated_at'), table_name='item_type_text')
    op.drop_index(op.f('ix_item_type_text_item_type_id'), table_name='item_type_text')
    op.drop_table('item_type_text')
    # ### end Alembic commands ###
