"""fixture-item_status

Revision ID: 1d68eea8cb90
Revises: caf3affe6c1a
Create Date: 2022-04-19 00:16:20.543504

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from sqlalchemy import MetaData, Table

revision = '1d68eea8cb90'
down_revision = 'caf3affe6c1a'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("item_status",))

    item_status = Table("item_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Available",
                "color": "green",
            },
            {
                "name": "Expired",
                "color": "red",
            },
            {
                "name": "Booked",
                "color": "blue",
            },
            {
                "name": "Maintenance",
                "color": "orange",
            },

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
