"""empty message

Revision ID: 278c7833cb6a
Revises: cb42a95bfc18
Create Date: 2021-12-23 23:32:09.844434

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '278c7833cb6a'
down_revision = 'cb42a95bfc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('day_picker_status', sa.Boolean(), nullable=False))
    op.add_column('booking_widget', sa.Column('time_picker_status', sa.Boolean(), nullable=False))
    op.add_column('booking_widget', sa.Column('date_range_picker_status', sa.Boolean(), nullable=False))
    op.drop_constraint('booking_widget_date_range_picker_key', 'booking_widget', type_='unique')
    op.drop_constraint('booking_widget_day_picker_key', 'booking_widget', type_='unique')
    op.drop_constraint('booking_widget_time_picker_key', 'booking_widget', type_='unique')
    op.create_unique_constraint(None, 'booking_widget', ['time_picker_status'])
    op.create_unique_constraint(None, 'booking_widget', ['date_range_picker_status'])
    op.create_unique_constraint(None, 'booking_widget', ['day_picker_status'])
    op.drop_column('booking_widget', 'day_picker')
    op.drop_column('booking_widget', 'time_picker')
    op.drop_column('booking_widget', 'date_range_picker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('date_range_picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('booking_widget', sa.Column('time_picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('booking_widget', sa.Column('day_picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.create_unique_constraint('booking_widget_time_picker_key', 'booking_widget', ['time_picker'])
    op.create_unique_constraint('booking_widget_day_picker_key', 'booking_widget', ['day_picker'])
    op.create_unique_constraint('booking_widget_date_range_picker_key', 'booking_widget', ['date_range_picker'])
    op.drop_column('booking_widget', 'date_range_picker_status')
    op.drop_column('booking_widget', 'time_picker_status')
    op.drop_column('booking_widget', 'day_picker_status')
    # ### end Alembic commands ###
