"""empty message

Revision ID: 2a228afa378b
Revises: 4373a9dec360
Create Date: 2022-02-19 18:35:04.069244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a228afa378b'
down_revision = '4373a9dec360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
