"""empty message

Revision ID: 3120a5a7bbd3
Revises: 4d4f132f300c
Create Date: 2022-01-24 22:07:33.359372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3120a5a7bbd3'
down_revision = '4d4f132f300c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
