"""empty message

Revision ID: 335a3bcd06b3
Revises: 0d6a1f5f9766
Create Date: 2022-06-30 12:43:41.201388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335a3bcd06b3'
down_revision = '0d6a1f5f9766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
