"""empty message

Revision ID: 39c0b6fcd9ec
Revises: a77efb2a1441
Create Date: 2022-01-08 15:48:52.369047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c0b6fcd9ec'
down_revision = 'a77efb2a1441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'booking_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('booking', 'status')
    op.add_column('order', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'order_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'status_id')
    op.add_column('booking', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'status_id')
    # ### end Alembic commands ###
