"""empty message

Revision ID: 4dc88d5c96ad
Revises: f7a78f91a774
Create Date: 2022-06-06 20:36:28.079646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc88d5c96ad'
down_revision = 'f7a78f91a774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
