"""empty message

Revision ID: 4f2207485ccc
Revises: bb066db1c8c6
Create Date: 2022-05-27 14:24:10.608578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2207485ccc'
down_revision = 'bb066db1c8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_method', 'description')
    # ### end Alembic commands ###
