"""empty message

Revision ID: 5352eb8e8c09
Revises: 5bd13f4f3883
Create Date: 2022-02-12 16:38:01.351538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5352eb8e8c09'
down_revision = '5bd13f4f3883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
