"""empty message

Revision ID: 575b455845e9
Revises: ebdb5fba8eac
Create Date: 2021-12-25 02:52:05.506952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575b455845e9'
down_revision = 'ebdb5fba8eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_updated_at'), 'tag', ['updated_at'], unique=False)
    op.create_table('item_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tag_updated_at'), 'item_tag', ['updated_at'], unique=False)
    op.drop_column('item', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_item_tag_updated_at'), table_name='item_tag')
    op.drop_table('item_tag')
    op.drop_index(op.f('ix_tag_updated_at'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
