"""empty message

Revision ID: 58982abc49f5
Revises: 39c0b6fcd9ec
Create Date: 2022-01-08 16:00:23.009477

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '58982abc49f5'
down_revision = '39c0b6fcd9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
