"""prices added

Revision ID: 5ba14c74688e
Revises: ff335eea48ef
Create Date: 2022-03-27 16:18:05.115079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba14c74688e'
down_revision = 'ff335eea48ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('actual_total_cost', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('actual_total_cost_after_tax', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'actual_total_cost_after_tax')
    op.drop_column('order', 'actual_total_cost')
    # ### end Alembic commands ###
