"""empty message

Revision ID: 5bd13f4f3883
Revises: de575b7d1b18
Create Date: 2022-02-12 16:04:47.646351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd13f4f3883'
down_revision = 'de575b7d1b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
