"""new soft deletion v3

Revision ID: 61ab8a975ab5
Revises: 9e091d7ece2a
Create Date: 2022-07-17 23:30:47.360714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ab8a975ab5'
down_revision = '9e091d7ece2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('False'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax', 'is_deleted')
    # ### end Alembic commands ###
