"""empty message

Revision ID: 6241905dfd8c
Revises: 88e52e6e4dca
Create Date: 2022-04-15 20:53:53.882486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6241905dfd8c'
down_revision = '88e52e6e4dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('logo_url_key', 'front_end_configs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('logo_url_key', 'front_end_configs', ['url'])
    # ### end Alembic commands ###
