"""empty message

Revision ID: 626e43f00257
Revises: f237b5060267
Create Date: 2022-06-28 01:51:44.030970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626e43f00257'
down_revision = 'f237b5060267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('cost_without_tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'cost_without_tax')
    # ### end Alembic commands ###
