"""empty message

Revision ID: 636e065cd1f8
Revises: b306da4ae8e9
Create Date: 2022-01-27 18:11:15.169603

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '636e065cd1f8'
down_revision = 'b306da4ae8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_column('item_subtype', 'prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('prices', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('item_subtype', 'price')
    # ### end Alembic commands ###
