"""empty message

Revision ID: 64d68f3411e3
Revises: 8f6988c6c5ab
Create Date: 2022-02-12 15:37:35.527895

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d68f3411e3'
down_revision = '8f6988c6c5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_months_prices_updated_at', table_name='months_prices')
    op.drop_table('months_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('months_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('January', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('February', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('March', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('April', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('May', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('June', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('July', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('August', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('September', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('October', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('November', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('December', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='months_prices_pkey'),
    sa.UniqueConstraint('April', name='months_prices_April_key'),
    sa.UniqueConstraint('August', name='months_prices_August_key'),
    sa.UniqueConstraint('December', name='months_prices_December_key'),
    sa.UniqueConstraint('February', name='months_prices_February_key'),
    sa.UniqueConstraint('January', name='months_prices_January_key'),
    sa.UniqueConstraint('July', name='months_prices_July_key'),
    sa.UniqueConstraint('June', name='months_prices_June_key'),
    sa.UniqueConstraint('March', name='months_prices_March_key'),
    sa.UniqueConstraint('May', name='months_prices_May_key'),
    sa.UniqueConstraint('November', name='months_prices_November_key'),
    sa.UniqueConstraint('October', name='months_prices_October_key'),
    sa.UniqueConstraint('September', name='months_prices_September_key')
    )
    op.create_index('ix_months_prices_updated_at', 'months_prices', ['updated_at'], unique=False)
    # ### end Alembic commands ###
