"""empty message

Revision ID: 65aa7dc4fab0
Revises: 4f2207485ccc
Create Date: 2022-05-30 23:31:07.228511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65aa7dc4fab0'
down_revision = '4f2207485ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('unique_key', sa.String(), nullable=False),
    sa.Column('paypal_method', sa.String(), nullable=False),
    sa.Column('payment_reference', sa.String(), nullable=False),
    sa.Column('voucher', sa.String(), nullable=True),
    sa.Column('price_paid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_backup_updated_at'), 'order_backup', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_backup_updated_at'), table_name='order_backup')
    op.drop_table('order_backup')
    # ### end Alembic commands ###
