"""empty message

Revision ID: 6a45f353728c
Revises: 3451dd176991
Create Date: 2022-04-15 22:48:04.952330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a45f353728c'
down_revision = '3451dd176991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_end_configs', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('front_end_configs', 'front_end_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_end_configs', 'front_end_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('front_end_configs', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
