"""empty message

Revision ID: 6a45f353728c
Revises: 3451dd176991
Create Date: 2022-04-15 22:48:04.952330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a45f353728c'
down_revision = '3451dd176991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_end_configs',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('logo', sa.VARCHAR(), nullable=True),
                    sa.Column('front_end_url', sa.VARCHAR(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_logo_updated_at'), 'front_end_configs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_logo_user_id'), 'front_end_configs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('front_end_configs', 'front_end_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('front_end_configs', 'logo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
