"""associate_emails_adde_updated

Revision ID: 6aec6d5c8cd3
Revises: a3a12526648c
Create Date: 2022-03-26 03:17:17.670915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aec6d5c8cd3'
down_revision = 'a3a12526648c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
