"""fixture-order_status

Revision ID: 6f1ac6c73bef
Revises: 1d68eea8cb90
Create Date: 2022-04-19 00:17:16.070115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import MetaData,Table

revision = '6f1ac6c73bef'
down_revision = '1d68eea8cb90'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("order_status",))

    item_status = Table("order_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Paid",
                "color": "green",
            },
            {
                "name": "Completed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            },
            {
                "name": "Payment Pending",
                "color": "yellow",
            },

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
