"""associate_emails_adde_updated2

Revision ID: 6f88a149e4d4
Revises: 6aec6d5c8cd3
Create Date: 2022-03-26 03:17:30.722607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f88a149e4d4'
down_revision = '6aec6d5c8cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
