"""empty message

Revision ID: 744bd979a728
Revises: b1a6512028b5
Create Date: 2022-01-19 00:03:02.883904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744bd979a728'
down_revision = 'b1a6512028b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
