"""empty message

Revision ID: 774dca0eadc1
Revises: 929d15ceb335
Create Date: 2022-01-08 15:20:28.066949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774dca0eadc1'
down_revision = '929d15ceb335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_booking_status_updated_at'), 'booking_status', ['updated_at'], unique=False)
    op.create_table('item_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_status_updated_at'), 'item_status', ['updated_at'], unique=False)
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_order_status_updated_at'), 'order_status', ['updated_at'], unique=False)
    op.add_column('tag', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'color')
    op.drop_index(op.f('ix_order_status_updated_at'), table_name='order_status')
    op.drop_table('order_status')
    op.drop_index(op.f('ix_item_status_updated_at'), table_name='item_status')
    op.drop_table('item_status')
    op.drop_index(op.f('ix_booking_status_updated_at'), table_name='booking_status')
    op.drop_table('booking_status')
    # ### end Alembic commands ###
