"""fixture-booking_status

Revision ID: 793c6eed6461
Revises: 6f1ac6c73bef
Create Date: 2022-04-19 00:18:02.491101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import MetaData,Table

revision = '793c6eed6461'
down_revision = '6f1ac6c73bef'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("booking_status",))

    item_status = Table("booking_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Active",
                "color": "green",
            },
            {
                "name": "Closed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            },
            {
                "name": "Pending",
                "color": "orange",
            }

        ],
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
