"""empty message

Revision ID: 7a3fa5b5eb49
Revises: 1d10b735d95f
Create Date: 2022-06-10 17:15:12.532013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3fa5b5eb49'
down_revision = '1d10b735d95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
