"""empty message

Revision ID: 8107e782105f
Revises: ac99fa64e3c2
Create Date: 2022-04-04 23:07:27.474594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8107e782105f'
down_revision = 'ac99fa64e3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('images', sa.String(length=500), nullable=False))
    op.drop_column('item', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item', 'images')
    # ### end Alembic commands ###
