"""empty message

Revision ID: 81b9a4765011
Revises: 
Create Date: 2022-03-31 00:07:04.426548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b9a4765011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_email',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_associate_email_updated_at'), 'associate_email', ['updated_at'], unique=False)
    op.create_table('booking_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_booking_status_updated_at'), 'booking_status', ['updated_at'], unique=False)
    op.create_table('booking_widget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('day_picker_status', sa.Boolean(), nullable=True),
    sa.Column('time_picker_status', sa.Boolean(), nullable=True),
    sa.Column('date_range_picker_status', sa.Boolean(), nullable=True),
    sa.Column('apply_vouchers_status', sa.Boolean(), nullable=True),
    sa.Column('apply_months_factor_status', sa.Boolean(), nullable=True),
    sa.Column('apply_location_factor_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_widget_updated_at'), 'booking_widget', ['updated_at'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_updated_at'), 'cart', ['updated_at'], unique=False)
    op.create_table('custom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_data_updated_at'), 'custom_data', ['updated_at'], unique=False)
    op.create_table('custom_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_custom_parameter_updated_at'), 'custom_parameter', ['updated_at'], unique=False)
    op.create_table('item_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_status_updated_at'), 'item_status', ['updated_at'], unique=False)
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('maintenance', sa.Integer(), nullable=False),
    sa.Column('delivery_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_type_updated_at'), 'item_type', ['updated_at'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_updated_at'), 'language', ['updated_at'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_factor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_location_updated_at'), 'location', ['updated_at'], unique=False)
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_order_status_updated_at'), 'order_status', ['updated_at'], unique=False)
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_payment_method_updated_at'), 'payment_method', ['updated_at'], unique=False)
    op.create_table('season',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('price_factor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_updated_at'), 'season', ['updated_at'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_updated_at'), 'tag', ['updated_at'], unique=False)
    op.create_table('tax',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tax_updated_at'), 'tax', ['updated_at'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('subscription', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_factor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_voucher_updated_at'), 'voucher', ['updated_at'], unique=False)
    op.create_table('item_subtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('person', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_subtype_updated_at'), 'item_subtype', ['updated_at'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('actual_total_cost', sa.Float(), nullable=False),
    sa.Column('effected_total_cost', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('order_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_updated_at'), 'order', ['updated_at'], unique=False)
    op.create_table('payment_tax',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_method.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_tax_updated_at'), 'payment_tax', ['updated_at'], unique=False)
    op.create_table('season_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_type_updated_at'), 'season_type', ['updated_at'], unique=False)
    op.create_table('associate_email_subtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('associate_email_id', sa.Integer(), nullable=False),
    sa.Column('item_subtype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associate_email_id'], ['associate_email.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_subtype_id'], ['item_subtype.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associate_email_subtype_updated_at'), 'associate_email_subtype', ['updated_at'], unique=False)
    op.create_table('day_picker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('item_subtype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_subtype_id'], ['item_subtype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_picker_updated_at'), 'day_picker', ['updated_at'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('item_status_id', sa.Integer(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('item_subtype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_status_id'], ['item_status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_subtype_id'], ['item_subtype.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_updated_at'), 'item', ['updated_at'], unique=False)
    op.create_table('order_custom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('custom_data_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_data_id'], ['custom_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_custom_data_updated_at'), 'order_custom_data', ['updated_at'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('booking_status_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_status_id'], ['booking_status.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_updated_at'), 'booking', ['updated_at'], unique=False)
    op.create_table('item_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_location_updated_at'), 'item_location', ['updated_at'], unique=False)
    op.create_table('item_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tag_updated_at'), 'item_tag', ['updated_at'], unique=False)
    op.create_table('time_picker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('day_picker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_picker_id'], ['day_picker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_picker_updated_at'), 'time_picker', ['updated_at'], unique=False)
    op.create_table('cart_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_bookings_updated_at'), 'cart_bookings', ['updated_at'], unique=False)
    op.create_table('order_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_bookings_updated_at'), 'order_bookings', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_bookings_updated_at'), table_name='order_bookings')
    op.drop_table('order_bookings')
    op.drop_index(op.f('ix_cart_bookings_updated_at'), table_name='cart_bookings')
    op.drop_table('cart_bookings')
    op.drop_index(op.f('ix_time_picker_updated_at'), table_name='time_picker')
    op.drop_table('time_picker')
    op.drop_index(op.f('ix_item_tag_updated_at'), table_name='item_tag')
    op.drop_table('item_tag')
    op.drop_index(op.f('ix_item_location_updated_at'), table_name='item_location')
    op.drop_table('item_location')
    op.drop_index(op.f('ix_booking_updated_at'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_order_custom_data_updated_at'), table_name='order_custom_data')
    op.drop_table('order_custom_data')
    op.drop_index(op.f('ix_item_updated_at'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_day_picker_updated_at'), table_name='day_picker')
    op.drop_table('day_picker')
    op.drop_index(op.f('ix_associate_email_subtype_updated_at'), table_name='associate_email_subtype')
    op.drop_table('associate_email_subtype')
    op.drop_index(op.f('ix_season_type_updated_at'), table_name='season_type')
    op.drop_table('season_type')
    op.drop_index(op.f('ix_payment_tax_updated_at'), table_name='payment_tax')
    op.drop_table('payment_tax')
    op.drop_index(op.f('ix_order_updated_at'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_item_subtype_updated_at'), table_name='item_subtype')
    op.drop_table('item_subtype')
    op.drop_index(op.f('ix_voucher_updated_at'), table_name='voucher')
    op.drop_table('voucher')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tax_updated_at'), table_name='tax')
    op.drop_table('tax')
    op.drop_index(op.f('ix_tag_updated_at'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_season_updated_at'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_payment_method_updated_at'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index(op.f('ix_order_status_updated_at'), table_name='order_status')
    op.drop_table('order_status')
    op.drop_index(op.f('ix_location_updated_at'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_language_updated_at'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_item_type_updated_at'), table_name='item_type')
    op.drop_table('item_type')
    op.drop_index(op.f('ix_item_status_updated_at'), table_name='item_status')
    op.drop_table('item_status')
    op.drop_index(op.f('ix_custom_parameter_updated_at'), table_name='custom_parameter')
    op.drop_table('custom_parameter')
    op.drop_index(op.f('ix_custom_data_updated_at'), table_name='custom_data')
    op.drop_table('custom_data')
    op.drop_index(op.f('ix_cart_updated_at'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_booking_widget_updated_at'), table_name='booking_widget')
    op.drop_table('booking_widget')
    op.drop_index(op.f('ix_booking_status_updated_at'), table_name='booking_status')
    op.drop_table('booking_status')
    op.drop_index(op.f('ix_associate_email_updated_at'), table_name='associate_email')
    op.drop_table('associate_email')
    # ### end Alembic commands ###
