"""empty message

Revision ID: 81c25631802b
Revises: 65c38d0f546f
Create Date: 2022-06-17 14:54:39.541379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c25631802b'
down_revision = '65c38d0f546f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_end_configs', sa.Column('link1_name', sa.String(), nullable=True))
    op.add_column('front_end_configs', sa.Column('link2_name', sa.String(), nullable=True))
    op.add_column('front_end_configs', sa.Column('link1', sa.String(), nullable=True))
    op.add_column('front_end_configs', sa.Column('link2', sa.String(), nullable=True))
    op.drop_column('front_end_configs', 'privacy_policy_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_end_configs', sa.Column('privacy_policy_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('front_end_configs', 'link2')
    op.drop_column('front_end_configs', 'link1')
    op.drop_column('front_end_configs', 'link2_name')
    op.drop_column('front_end_configs', 'link1_name')
    # ### end Alembic commands ###
