"""empty message

Revision ID: 83a78bbf887c
Revises: 575b455845e9
Create Date: 2021-12-25 23:21:48.955305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a78bbf887c'
down_revision = '575b455845e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_user_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('item_user_id_fkey', 'item', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
