"""empty message

Revision ID: 88e52e6e4dca
Revises: bf6d487edaf1
Create Date: 2022-04-14 03:48:33.484706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e52e6e4dca'
down_revision = 'bf6d487edaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
