"""empty message

Revision ID: 8ab73f2477ee
Revises: 040ba8185928
Create Date: 2022-01-27 21:50:34.888843

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8ab73f2477ee'
down_revision = '040ba8185928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('language', 'statuss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('statuss', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('language', 'status')
    # ### end Alembic commands ###
