"""item fixture

Revision ID: 8b65320cce0b
Revises: bf1c95c83147
Create Date: 2022-03-31 00:19:56.797841

"""
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import MetaData, Table

revision = '8b65320cce0b'
down_revision = 'bf1c95c83147'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("item_status",))

    item_status = Table("item_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Available",
                "color": "green",
            },
            {
                "name": "Expired",
                "color": "red",
            },
            {
                "name": "Booked",
                "color": "blue",
            },
            {
                "name": "Maintenance",
                "color": "orange",
            },

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
