"""empty message

Revision ID: 8f6988c6c5ab
Revises: 8ab73f2477ee
Create Date: 2022-02-10 18:57:15.619444

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8f6988c6c5ab'
down_revision = '8ab73f2477ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_widget',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('day_picker_status', sa.Boolean(), nullable=True),
    sa.Column('time_picker_status', sa.Boolean(), nullable=True),
    sa.Column('date_range_picker_status', sa.Boolean(), nullable=True),
    sa.Column('apply_vouchers_status', sa.Boolean(), nullable=True),
    sa.Column('apply_months_factor_status', sa.Boolean(), nullable=True),
    sa.Column('apply_location_factor_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_widget_updated_at'), 'booking_widget', ['updated_at'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_factor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_location_updated_at'), 'location', ['updated_at'], unique=False)
    op.create_table('months_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('January', sa.Integer(), nullable=False),
    sa.Column('February', sa.Integer(), nullable=False),
    sa.Column('March', sa.Integer(), nullable=False),
    sa.Column('April', sa.Integer(), nullable=False),
    sa.Column('May', sa.Integer(), nullable=False),
    sa.Column('June', sa.Integer(), nullable=False),
    sa.Column('July', sa.Integer(), nullable=False),
    sa.Column('August', sa.Integer(), nullable=False),
    sa.Column('September', sa.Integer(), nullable=False),
    sa.Column('October', sa.Integer(), nullable=False),
    sa.Column('November', sa.Integer(), nullable=False),
    sa.Column('December', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('April'),
    sa.UniqueConstraint('August'),
    sa.UniqueConstraint('December'),
    sa.UniqueConstraint('February'),
    sa.UniqueConstraint('January'),
    sa.UniqueConstraint('July'),
    sa.UniqueConstraint('June'),
    sa.UniqueConstraint('March'),
    sa.UniqueConstraint('May'),
    sa.UniqueConstraint('November'),
    sa.UniqueConstraint('October'),
    sa.UniqueConstraint('September')
    )
    op.create_index(op.f('ix_months_prices_updated_at'), 'months_prices', ['updated_at'], unique=False)
    op.create_table('voucher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_factor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_voucher_updated_at'), 'voucher', ['updated_at'], unique=False)
    op.create_table('item_location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_location_updated_at'), 'item_location', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_location_updated_at'), table_name='item_location')
    op.drop_table('item_location')
    op.drop_index(op.f('ix_voucher_updated_at'), table_name='voucher')
    op.drop_table('voucher')
    op.drop_index(op.f('ix_months_prices_updated_at'), table_name='months_prices')
    op.drop_table('months_prices')
    op.drop_index(op.f('ix_location_updated_at'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_booking_widget_updated_at'), table_name='booking_widget')
    op.drop_table('booking_widget')
    # ### end Alembic commands ###
