"""empty message

Revision ID: 929d15ceb335
Revises: a305787421ab
Create Date: 2021-12-30 00:47:38.019668

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '929d15ceb335'
down_revision = 'a305787421ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_cost')
    # ### end Alembic commands ###
