"""empty message

Revision ID: 97be1251f26d
Revises: 744bd979a728
Create Date: 2022-01-19 20:19:57.094042

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '97be1251f26d'
down_revision = '744bd979a728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
