"""new fields added for cost calculations

Revision ID: 99bf4c7ad78b
Revises: 19b5fa8811f7
Create Date: 2022-04-28 03:30:05.960537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bf4c7ad78b'
down_revision = '19b5fa8811f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('least_price', sa.Float(), nullable=True))
    op.add_column('item_subtype', sa.Column('discount_after_higher_price', sa.Integer(), nullable=True))
    op.add_column('item_subtype', sa.Column('same_price_days', sa.Integer(), nullable=True))
    op.add_column('item_type', sa.Column('show_time_picker', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_type', 'show_time_picker')
    op.drop_column('item_subtype', 'same_price_days')
    op.drop_column('item_subtype', 'discount_after_higher_price')
    op.drop_column('item_subtype', 'least_price')
    # ### end Alembic commands ###
