"""unique const removed

Revision ID: 9a5fcf859581
Revises: c8720a0a9019
Create Date: 2022-04-19 03:38:10.627161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5fcf859581'
down_revision = 'c8720a0a9019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('associate_email_email_key', 'associate_email', type_='unique')
    op.drop_constraint('custom_parameter_name_key', 'custom_parameter', type_='unique')
    op.drop_constraint('item_status_name_key', 'item_status', type_='unique')
    op.drop_constraint('item_subtype_name_key', 'item_subtype', type_='unique')
    op.drop_constraint('item_type_name_key', 'item_type', type_='unique')
    op.drop_constraint('location_name_key', 'location', type_='unique')
    op.drop_constraint('payment_method_name_key', 'payment_method', type_='unique')
    op.drop_constraint('tag_name_key', 'tag', type_='unique')
    op.drop_constraint('tax_name_key', 'tax', type_='unique')
    op.drop_constraint('voucher_code_key', 'voucher', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('voucher_code_key', 'voucher', ['code'])
    op.create_unique_constraint('tax_name_key', 'tax', ['name'])
    op.create_unique_constraint('tag_name_key', 'tag', ['name'])
    op.create_unique_constraint('payment_method_name_key', 'payment_method', ['name'])
    op.create_unique_constraint('location_name_key', 'location', ['name'])
    op.create_unique_constraint('item_type_name_key', 'item_type', ['name'])
    op.create_unique_constraint('item_subtype_name_key', 'item_subtype', ['name'])
    op.create_unique_constraint('item_status_name_key', 'item_status', ['name'])
    op.create_unique_constraint('custom_parameter_name_key', 'custom_parameter', ['name'])
    op.create_unique_constraint('associate_email_email_key', 'associate_email', ['email'])
    # ### end Alembic commands ###
