"""empty message

Revision ID: 9e45384ec7c7
Revises: 65aa7dc4fab0
Create Date: 2022-05-30 23:31:46.738059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e45384ec7c7'
down_revision = '65aa7dc4fab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
