"""empty message

Revision ID: a09a779a8127
Revises: e12f9374a09c
Create Date: 2022-01-24 02:38:57.482896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09a779a8127'
down_revision = 'e12f9374a09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
