"""empty message

Revision ID: a305787421ab
Revises: d0a0fdca0356
Create Date: 2021-12-26 23:18:58.904620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a305787421ab'
down_revision = 'd0a0fdca0356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_column('booking', 'start_time1')
    op.drop_column('booking', 'end_time1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('end_time1', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('start_time1', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'end_time')
    op.drop_column('booking', 'start_time')
    # ### end Alembic commands ###
