"""associate_emails_added

Revision ID: a3a12526648c
Revises: cf845114da13
Create Date: 2022-03-26 03:16:37.644824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3a12526648c'
down_revision = 'cf845114da13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
