"""empty message

Revision ID: a3d377e8931f
Revises: cf5e40c264e0
Create Date: 2022-01-24 19:14:25.178025

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a3d377e8931f'
down_revision = 'cf5e40c264e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
