"""empty message

Revision ID: a77efb2a1441
Revises: 774dca0eadc1
Create Date: 2022-01-08 15:34:48.908689

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a77efb2a1441'
down_revision = '774dca0eadc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'item_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'status_id')
    # ### end Alembic commands ###
