"""empty message

Revision ID: ac99fa64e3c2
Revises: 8b65320cce0b
Create Date: 2022-04-04 23:06:33.377878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac99fa64e3c2'
down_revision = '8b65320cce0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
