"""order fixture

Revision ID: b0fd03ab3c63
Revises: 81b9a4765011
Create Date: 2022-03-31 00:09:48.081401

"""
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import MetaData, Table

revision = 'b0fd03ab3c63'
down_revision = '81b9a4765011'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("order_status",))

    item_status = Table("order_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Paid",
                "color": "green",
            },
            {
                "name": "Completed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            },
            {
                "name": "Payment Pending",
                "color": "yellow",
            },

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
