"""empty message

Revision ID: b1a6512028b5
Revises: 58982abc49f5
Create Date: 2022-01-18 21:45:37.718749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a6512028b5'
down_revision = '58982abc49f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_status_id', sa.Integer(), nullable=True))
    op.drop_constraint('booking_status_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'booking_status', ['booking_status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('booking', 'status_id')
    op.add_column('item', sa.Column('item_status_id', sa.Integer(), nullable=True))
    op.drop_constraint('item_status_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'item_status', ['item_status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'status_id')
    op.add_column('order', sa.Column('order_status_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_status_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'order_status', ['order_status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order', 'status_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_status_id_fkey', 'order', 'order_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order', 'order_status_id')
    op.add_column('item', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_status_id_fkey', 'item', 'item_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'item_status_id')
    op.add_column('booking', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_status_id_fkey', 'booking', 'booking_status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('booking', 'booking_status_id')
    # ### end Alembic commands ###
