"""empty message

Revision ID: b306da4ae8e9
Revises: c5c45175831a
Create Date: 2022-01-27 18:06:22.318461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b306da4ae8e9'
down_revision = 'c5c45175831a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('prices', sa.Integer(), nullable=False))
    op.drop_column('item_subtype', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('item_subtype', 'prices')
    # ### end Alembic commands ###
