"""empty message

Revision ID: b737f39cf137
Revises: 55fa4a4af763
Create Date: 2021-12-23 23:27:22.894906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b737f39cf137'
down_revision = '55fa4a4af763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('date_picker', sa.Boolean(), nullable=False))
    op.add_column('booking_widget', sa.Column('time_picker', sa.Boolean(), nullable=False))
    op.add_column('booking_widget', sa.Column('date_range_picker', sa.Boolean(), nullable=False))
    op.drop_constraint('booking_widget_date_Picker_key', 'booking_widget', type_='unique')
    op.drop_constraint('booking_widget_date_range_Picker_key', 'booking_widget', type_='unique')
    op.drop_constraint('booking_widget_time_Picker_key', 'booking_widget', type_='unique')
    op.create_unique_constraint(None, 'booking_widget', ['date_picker'])
    op.create_unique_constraint(None, 'booking_widget', ['date_range_picker'])
    op.create_unique_constraint(None, 'booking_widget', ['time_picker'])
    op.drop_column('booking_widget', 'date_Picker')
    op.drop_column('booking_widget', 'date_range_Picker')
    op.drop_column('booking_widget', 'time_Picker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('time_Picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('booking_widget', sa.Column('date_range_Picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('booking_widget', sa.Column('date_Picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.create_unique_constraint('booking_widget_time_Picker_key', 'booking_widget', ['time_Picker'])
    op.create_unique_constraint('booking_widget_date_range_Picker_key', 'booking_widget', ['date_range_Picker'])
    op.create_unique_constraint('booking_widget_date_Picker_key', 'booking_widget', ['date_Picker'])
    op.drop_column('booking_widget', 'date_range_picker')
    op.drop_column('booking_widget', 'time_picker')
    op.drop_column('booking_widget', 'date_picker')
    # ### end Alembic commands ###
