"""empty message

Revision ID: bacebded6c51
Revises: 6b912b188dba
Create Date: 2022-04-14 00:12:10.444521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacebded6c51'
down_revision = '6b912b188dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
