"""empty message

Revision ID: bb066db1c8c6
Revises: 99bf4c7ad78b
Create Date: 2022-05-24 16:13:22.269186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb066db1c8c6'
down_revision = '99bf4c7ad78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_booking_location_id'), 'booking', ['location_id'], unique=False)
    op.create_foreign_key(None, 'booking', 'location', ['location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_index(op.f('ix_booking_location_id'), table_name='booking')
    op.drop_column('booking', 'location_id')
    # ### end Alembic commands ###
