"""status_fixture_order_status

Revision ID: bc33b3809d3f
Revises: e8bbf4c2e2b3
Create Date: 2022-03-22 19:11:27.212781

"""
from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision = 'bc33b3809d3f'
down_revision = 'e8bbf4c2e2b3'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("order_status",))

    item_status = Table("order_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Paid",
                "color": "green",
            },
            {
                "name": "Completed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            },
            {
                "name": "Payment Pending",
                "color": "yellow",
            },

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
