"""booking fixture

Revision ID: bf1c95c83147
Revises: b0fd03ab3c63
Create Date: 2022-03-31 00:13:46.622879

"""
from alembic import op

# revision identifiers, used by Alembic.
from sqlalchemy import MetaData, Table

revision = 'bf1c95c83147'
down_revision = 'b0fd03ab3c63'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("booking_status",))

    item_status = Table("booking_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Active",
                "color": "green",
            },
            {
                "name": "Closed",
                "color": "blue",
            },
            {
                "name": "Cancelled",
                "color": "red",
            }

        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
