"""empty message

Revision ID: c2f7b6f49df5
Revises: ea4725677db8
Create Date: 2022-01-24 22:17:10.374475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f7b6f49df5'
down_revision = 'ea4725677db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_data_updated_at'), 'custom_data', ['updated_at'], unique=False)
    op.create_table('custom_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_custom_parameter_updated_at'), 'custom_parameter', ['updated_at'], unique=False)
    op.create_table('order_custom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('custom_data_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_data_id'], ['custom_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_custom_data_updated_at'), 'order_custom_data', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_custom_data_updated_at'), table_name='order_custom_data')
    op.drop_table('order_custom_data')
    op.drop_index(op.f('ix_custom_parameter_updated_at'), table_name='custom_parameter')
    op.drop_table('custom_parameter')
    op.drop_index(op.f('ix_custom_data_updated_at'), table_name='custom_data')
    op.drop_table('custom_data')
    # ### end Alembic commands ###
