"""empty message

Revision ID: c5c45175831a
Revises: 64080e0fbd2c
Create Date: 2022-01-27 18:05:20.491761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c45175831a'
down_revision = '64080e0fbd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
