"""test

Revision ID: c8720a0a9019
Revises: 793c6eed6461
Create Date: 2022-04-19 00:21:58.793061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8720a0a9019'
down_revision = '793c6eed6461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
