"""empty message

Revision ID: cb047b3934d5
Revises: bacebded6c51
Create Date: 2022-04-14 00:51:04.756125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb047b3934d5'
down_revision = 'bacebded6c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_parameter', sa.Column('mandatory', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_parameter', 'mandatory')
    # ### end Alembic commands ###
