"""empty message

Revision ID: cb42a95bfc18
Revises: b737f39cf137
Create Date: 2021-12-23 23:29:18.098829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cb42a95bfc18'
down_revision = 'b737f39cf137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('day_picker', sa.Boolean(), nullable=False))
    op.drop_constraint('booking_widget_date_picker_key', 'booking_widget', type_='unique')
    op.create_unique_constraint(None, 'booking_widget', ['day_picker'])
    op.drop_column('booking_widget', 'date_picker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_widget', sa.Column('date_picker', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'booking_widget', type_='unique')
    op.create_unique_constraint('booking_widget_date_picker_key', 'booking_widget', ['date_picker'])
    op.drop_column('booking_widget', 'day_picker')
    # ### end Alembic commands ###
