"""empty message

Revision ID: cf5e40c264e0
Revises: aaef49cf57b2
Create Date: 2022-01-24 18:11:45.731737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5e40c264e0'
down_revision = 'aaef49cf57b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('day_picker', 'item_subtype_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('day_picker_item_subtype_id_key', 'day_picker', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('day_picker_item_subtype_id_key', 'day_picker', ['item_subtype_id'])
    op.alter_column('day_picker', 'item_subtype_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
