"""associate_emails_added

Revision ID: cf845114da13
Revises: df2fed2e9339
Create Date: 2022-03-26 03:13:16.090577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf845114da13'
down_revision = 'df2fed2e9339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
