"""empty message

Revision ID: d0a0fdca0356
Revises: e45c18fac446
Create Date: 2021-12-26 23:18:45.855556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a0fdca0356'
down_revision = 'e45c18fac446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_time1', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('end_time1', sa.DateTime(), nullable=False))
    op.add_column('booking', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('booking', 'end_time')
    op.drop_column('booking', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'status')
    op.drop_column('booking', 'end_time1')
    op.drop_column('booking', 'start_time1')
    # ### end Alembic commands ###
