"""day_picker and time_picker updated

Revision ID: d2bcca5f1c72
Revises: 9a5fcf859581
Create Date: 2022-04-19 18:03:01.510928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bcca5f1c72'
down_revision = '9a5fcf859581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_picker', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_day_picker_user_id'), 'day_picker', ['user_id'], unique=False)
    op.create_foreign_key(None, 'day_picker', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('time_picker', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_time_picker_user_id'), 'time_picker', ['user_id'], unique=False)
    op.create_foreign_key(None, 'time_picker', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_picker', type_='foreignkey')
    op.drop_index(op.f('ix_time_picker_user_id'), table_name='time_picker')
    op.drop_column('time_picker', 'user_id')
    op.drop_constraint(None, 'day_picker', type_='foreignkey')
    op.drop_index(op.f('ix_day_picker_user_id'), table_name='day_picker')
    op.drop_column('day_picker', 'user_id')
    # ### end Alembic commands ###
