"""empty message

Revision ID: d6f4673bbdfd
Revises: dd0cf1bb4338
Create Date: 2022-04-13 03:21:43.272458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f4673bbdfd'
down_revision = 'dd0cf1bb4338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
