"""empty message

Revision ID: d9e7b9767fa0
Revises: 3631258ea2a4
Create Date: 2022-04-05 01:48:44.569799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7b9767fa0'
down_revision = '3631258ea2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_key', sa.String(), nullable=False))
    op.add_column('item_subtype', sa.Column('image_key', sa.String(), nullable=False))
    op.add_column('item_type', sa.Column('image_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_type', 'image_key')
    op.drop_column('item_subtype', 'image_key')
    op.drop_column('item', 'image_key')
    # ### end Alembic commands ###
