"""empty message

Revision ID: dad2df5edaa0
Revises: f5e46fa2f307
Create Date: 2022-03-24 22:25:15.065372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad2df5edaa0'
down_revision = 'f5e46fa2f307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
