"""empty message

Revision ID: dd0cf1bb4338
Revises: e614e84a43dd
Create Date: 2022-04-13 02:27:15.268327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0cf1bb4338'
down_revision = 'e614e84a43dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_item_subtype_user_key', table_name='item_subtype')
    op.create_index(op.f('ix_item_subtype_user_id'), 'item_subtype', ['user_id'], unique=False)
    op.drop_constraint('item_subtype_user_key_fkey', 'item_subtype', type_='foreignkey')
    op.create_foreign_key(None, 'item_subtype', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item_subtype', 'user_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_subtype', sa.Column('user_key', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item_subtype', type_='foreignkey')
    op.create_foreign_key('item_subtype_user_key_fkey', 'item_subtype', 'user', ['user_key'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_item_subtype_user_id'), table_name='item_subtype')
    op.create_index('ix_item_subtype_user_key', 'item_subtype', ['user_key'], unique=False)
    op.drop_column('item_subtype', 'user_id')
    # ### end Alembic commands ###
