"""empty message

Revision ID: df2fed2e9339
Revises: dad2df5edaa0
Create Date: 2022-03-25 23:43:59.861838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2fed2e9339'
down_revision = 'dad2df5edaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'time_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('time_period', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
