"""empty message

Revision ID: e12f9374a09c
Revises: 05cc1a8cc229
Create Date: 2022-01-19 20:36:12.317010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e12f9374a09c'
down_revision = '05cc1a8cc229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('status', sa.Boolean(), nullable=False))
    op.drop_column('payment_method', 'statuss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_method', sa.Column('statuss', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('payment_method', 'status')
    # ### end Alembic commands ###
