"""empty message

Revision ID: e45c18fac446
Revises: 03ecc69cd26c
Create Date: 2021-12-25 23:42:16.125669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45c18fac446'
down_revision = '03ecc69cd26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.String(), nullable=False))
    op.add_column('item', sa.Column('person', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'person')
    op.drop_column('item', 'status')
    # ### end Alembic commands ###
