"""empty message

Revision ID: e58858f164f4
Revises: 1bbad1f20e12
Create Date: 2021-11-25 01:57:00.522880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58858f164f4'
down_revision = '1bbad1f20e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('maintenance', sa.Integer(), nullable=False),
    sa.Column('delivery_available', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maintenance')
    )
    op.create_index(op.f('ix_item_type_updated_at'), 'item_type', ['updated_at'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_email')
    )
    op.create_index(op.f('ix_order_updated_at'), 'order', ['updated_at'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_time'),
    sa.UniqueConstraint('location')
    )
    op.create_index(op.f('ix_booking_updated_at'), 'booking', ['updated_at'], unique=False)
    op.create_table('order_bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_bookings_updated_at'), 'order_bookings', ['updated_at'], unique=False)
    op.add_column('item', sa.Column('item_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item', 'item_type', ['item_type_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'subscription',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'subscription',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'item_type_id')
    op.drop_index(op.f('ix_order_bookings_updated_at'), table_name='order_bookings')
    op.drop_table('order_bookings')
    op.drop_index(op.f('ix_booking_updated_at'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_order_updated_at'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_item_type_updated_at'), table_name='item_type')
    op.drop_table('item_type')
    # ### end Alembic commands ###
