"""status_fixture_item_status

Revision ID: e8bbf4c2e2b3
Revises: 04801025b12f
Create Date: 2022-03-22 19:06:28.595353

"""
from alembic import op
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.

revision = 'e8bbf4c2e2b3'
down_revision = '04801025b12f'
branch_labels = None
depends_on = None


def upgrade():
    meta = MetaData(bind=op.get_bind())

    meta.reflect(only=("item_status",))

    item_status = Table("item_status", meta)
    op.bulk_insert(
        item_status,
        [
            {
                "name": "Available",
                "color": "green",
            },
            {
                "name": "Expired",
                "color": "red",
            },
            {
                "name": "Booked",
                "color": "blue",
            },
            {
                "name": "Maintenance",
                "color": "orange",
            },

        ],
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
