"""empty message

Revision ID: ea4725677db8
Revises: 3120a5a7bbd3
Create Date: 2022-01-24 22:16:06.026876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea4725677db8'
down_revision = '3120a5a7bbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
