"""empty message

Revision ID: ebdb5fba8eac
Revises: 6a1cceb8559a
Create Date: 2021-12-23 23:58:28.387269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ebdb5fba8eac'
down_revision = '6a1cceb8559a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item_type', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_type', type_='unique')
    # ### end Alembic commands ###
