"""empty message

Revision ID: ec79d42ef913
Revises: c2f7b6f49df5
Create Date: 2022-01-24 22:40:18.637772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec79d42ef913'
down_revision = 'c2f7b6f49df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
