"""cart_order_relation_added

Revision ID: f5e46fa2f307
Revises: 8741bdb4a6df
Create Date: 2022-03-24 22:20:15.034595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e46fa2f307'
down_revision = '8741bdb4a6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('cart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'cart', ['cart_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'cart_id')
    # ### end Alembic commands ###
