"""associate_emails_adde_updated2

Revision ID: ff335eea48ef
Revises: 6f88a149e4d4
Create Date: 2022-03-26 03:18:01.673631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff335eea48ef'
down_revision = '6f88a149e4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associate_email_subtype',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('associate_email_id', sa.Integer(), nullable=False),
    sa.Column('item_subtype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['associate_email_id'], ['associate_email.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_subtype_id'], ['item_subtype.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associate_email_subtype_updated_at'), 'associate_email_subtype', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_associate_email_subtype_updated_at'), table_name='associate_email_subtype')
    op.drop_table('associate_email_subtype')
    # ### end Alembic commands ###
